# ──────────────────────────────────────────────────────────────────────────────
# PLAYER ID MAP  (slug + ATP 4-char code from atptour.com URLs)
# Add any player: open atptour.com/en/players/{slug}/{ID}/overview
# ──────────────────────────────────────────────────────────────────────────────

PLAYER_ID_MAP = {
    "walton":       ("Adam Walton",          "adam-walton",          "W09E"),
    "rodesch":      ("Chris Rodesch",        "chris-rodesch",        "R0E0"),
    "alcaraz":      ("Carlos Alcaraz",       "carlos-alcaraz",       "A0E2"),
    "djokovic":     ("Novak Djokovic",       "novak-djokovic",       "D643"),
    "sinner":       ("Jannik Sinner",        "jannik-sinner",        "S0AG"),
    "medvedev":     ("Daniil Medvedev",      "daniil-medvedev",      "M0GR"),
    "zverev":       ("Alexander Zverev",     "alexander-zverev",     "Z355"),
    "fritz":        ("Taylor Fritz",         "taylor-fritz",         "F324"),
    "hurkacz":      ("Hubert Hurkacz",       "hubert-hurkacz",       "H817"),
    "draper":       ("Jack Draper",          "jack-draper",          "D0EE"),
    "de minaur":    ("Alex de Minaur",       "alex-de-minaur",       "D875"),
    "shelton":      ("Ben Shelton",          "ben-shelton",          "S0SR"),
    "paul":         ("Tommy Paul",           "tommy-paul",           "P822"),
    "tiafoe":       ("Frances Tiafoe",       "frances-tiafoe",       "T782"),
    "kecmanovic":   ("Miomir Kecmanovic",    "miomir-kecmanovic",    "K0CM"),
    "jarry":        ("Nicolas Jarry",        "nicolas-jarry",        "J918"),
    "bellucci":     ("Mattia Bellucci",      "mattia-bellucci",      "B0BW"),
    "maestrelli":   ("Francesco Maestrelli", "francesco-maestrelli", "M0TA"),
    "watanuki":     ("Yosuke Watanuki",      "yosuke-watanuki",      "W0AK"),
    "tsitsipas":    ("Stefanos Tsitsipas",   "stefanos-tsitsipas",   "T615"),
    "ruud":         ("Casper Ruud",          "casper-ruud",          "R0CR"),
    "rublev":       ("Andrey Rublev",        "andrey-rublev",        "R0BL"),
    "halys":        ("Quentin Halys",        "quentin-halys",        "H918"),
    "diallo":       ("Gabriel Diallo",       "gabriel-diallo",       "D0HJ"),
    "schoolkate":   ("Tristan Schoolkate",   "tristan-schoolkate",   "S0GR"),
    "mpetshi":      ("Giovanni Mpetshi",     "giovanni-mpetshi",     "M0PS"),
    "berrettini":   ("Matteo Berrettini",    "matteo-berrettini",    "B718"),
    "norrie":       ("Cameron Norrie",       "cameron-norrie",       "N552"),
    "wawrinka":     ("Stan Wawrinka",        "stan-wawrinka",        "W451"),
    "cilic":        ("Marin Cilic",          "marin-cilic",          "C977"),
    "kyrgios":      ("Nick Kyrgios",         "nick-kyrgios",         "K402"),
    "shapovalov":   ("Denis Shapovalov",     "denis-shapovalov",     "S0BW"),
    "dimitrov":     ("Grigor Dimitrov",      "grigor-dimitrov",      "D875"),
    "auger":        ("Felix Auger-Aliassime","felix-auger-aliassime","A0AP"),
    "khachanov":    ("Karen Khachanov",      "karen-khachanov",      "K780"),
    "struff":       ("Jan-Lennard Struff",   "jan-lennard-struff",   "S888"),
    "humbert":      ("Ugo Humbert",          "ugo-humbert",          "H939"),
    "musetti":      ("Lorenzo Musetti",      "lorenzo-musetti",      "M0MU"),
    "cobolli":      ("Flavio Cobolli",       "flavio-cobolli",       "C0CB"),
    "navone":       ("Mariano Navone",       "mariano-navone",       "N0AV"),
    "etcheverry":   ("Tomas Etcheverry",     "tomas-etcheverry",     "E0TC"),
    "cerundolo":    ("Francisco Cerundolo",  "francisco-cerundolo",  "C0CE"),
    "baez":         ("Sebastian Baez",       "sebastian-baez",       "B0BZ"),
    "davidovich":   ("Alejandro Davidovich", "alejandro-davidovich", "D0AF"),
    "bublik":       ("Alexander Bublik",     "alexander-bublik",     "B0BU"),
    "korda":        ("Sebastian Korda",      "sebastian-korda",      "K0AH"),
    "landaluce":    ("Martin Landaluce",     "martin-landaluce",     "L0IL"),
    "lehecka":      ("Jiri Lehecka",         "jiri-lehecka",         "L0BV"),
    "vacherot":     ("Valentin Vacherot",    "valentin-vacherot",    "VA25"),
    "fils":         ("Arthur Fils",          "arthur-fils",          "F0F1"),
    "michelsen":    ("Alex Michelsen",       "alex-michelsen",       "M0QI"),
    "atmane":       ("Terence Atmane",       "terence-atmane",       "A0GC"),
}

# ──────────────────────────────────────────────────────────────────────────────
# STATIC CURATED PROFILES  (as of March 16, 2026 — update periodically)
# Source: atptour.com + our earlier research session
# ──────────────────────────────────────────────────────────────────────────────

STATIC_PROFILES = {
    "W09E": dict(  # Adam Walton
        ranking=85, age=26, height_cm=183, plays="Right-handed",
        turned_pro=2022, career_wins=183, career_losses=116,
        career_high_rank=74,
        hard_wins=158, hard_losses=75,
        clay_wins=0,   clay_losses=2,
        grass_wins=0,  grass_losses=1,
        ytd_wins=7,    ytd_losses=10,
        # L10 going into Miami qualifying (most recent last)
        # L vs Bellucci SF, W vs Kecmanovic QF, W vs Andrade R2,
        # W vs Jarry R1 (Cap Cana), L vs Zverev R2 (Delray),
        # W vs Bonzi R1 (Delray), L vs Harris Q (Delray),
        # L vs Hijikata R1 (Brisbane), W vs Delaney Q, L vs Halys Q
        recent_form=["L","W","W","W","L","W","L","L","W","L"],
    ),
    "R0E0": dict(  # Chris Rodesch
        ranking=137, age=24, height_cm=198, plays="Right-handed",
        turned_pro=2024, career_wins=117, career_losses=47,
        career_high_rank=137,
        hard_wins=67,  hard_losses=26,
        clay_wins=50,  clay_losses=17,
        grass_wins=1,  grass_losses=2,
        ytd_wins=13,   ytd_losses=2,
        # 10-match winning streak: 2x Oeiras 1 + Oeiras 2 (Jan-Feb 2026)
        recent_form=["W","W","W","W","W","W","W","W","W","W"],
    ),
    "M0TA": dict(  # Francesco Maestrelli
        ranking=162, age=23, height_cm=185, plays="Right-handed",
        turned_pro=2021, career_wins=95, career_losses=60,
        career_high_rank=133,
        hard_wins=40, hard_losses=28,
        clay_wins=45, clay_losses=25,
        grass_wins=2,  grass_losses=4,
        ytd_wins=5,   ytd_losses=4,
        recent_form=["W","L","W","W","L","L","W","L","W","W"],
    ),
    "W0AK": dict(  # Yosuke Watanuki
        ranking=191, age=26, height_cm=175, plays="Right-handed",
        turned_pro=2018, career_wins=78, career_losses=62,
        career_high_rank=148,
        hard_wins=38, hard_losses=30,
        clay_wins=28, clay_losses=22,
        grass_wins=2,  grass_losses=3,
        ytd_wins=4,   ytd_losses=5,
        recent_form=["L","W","L","W","L","W","W","L","L","W"],
    ),
}

# ──────────────────────────────────────────────────────────────────────────────
# WTA STATIC PROFILES  (Miami 2026 — curées mars 2026)
# ──────────────────────────────────────────────────────────────────────────────

# NOTE: WTA recent_form lists are static, frozen at last profile edit date.
# Live fetch is skipped for WTA players because _top_up_from_api() only
# runs when profile.recent_form is empty, and all WTA_PROFILES entries
# include a non-empty recent_form list.

WTA_PROFILES = {
    "maria sakkari": dict(
        full_name="Maria Sakkari", ranking=33, age=30, height_cm=175,
        plays="Right-handed", turned_pro=2010,
        career_wins=166, career_losses=132, career_high_rank=3,
        # Fixed: hard_wins previously = career_wins (copy-paste error).
        # Corrected to 55.7% hard rate per user spec; clay/grass scaled proportionally
        # so that hard+clay+grass == career total (166 W / 132 L).
        hard_wins=95,  hard_losses=68,   # 57.2% of wins, 58.3% win rate on hard
        clay_wins=54,  clay_losses=42,   # 32.5% of wins, 56.2% win rate on clay
        grass_wins=17, grass_losses=22,  # 10.2% of wins, 43.6% win rate on grass
        ytd_wins=8, ytd_losses=5,
        recent_form=["W","L","W","W","L","W","L","W","W","L"],
    ),
    "katerina siniakova": dict(
        full_name="Katerina Siniakova", ranking=42, age=26, height_cm=171,
        plays="Right-handed", turned_pro=2012,
        career_wins=185, career_losses=138, career_high_rank=22,
        hard_wins=95,  hard_losses=78,
        clay_wins=72,  clay_losses=48,
        grass_wins=18, grass_losses=12,
        ytd_wins=12, ytd_losses=5,
        recent_form=["W","W","W","L","W","W","L","W","W","L"],
    ),
    "dayana yastremska": dict(
        full_name="Dayana Yastremska", ranking=54, age=24, height_cm=168,
        plays="Right-handed", turned_pro=2017,
        career_wins=210, career_losses=148, career_high_rank=20,
        hard_wins=108, hard_losses=78,
        clay_wins=72,  clay_losses=52,
        grass_wins=30, grass_losses=18,
        ytd_wins=5, ytd_losses=8,
        recent_form=["W","W","L","W","W","W","L","W","W","W"],
    ),
    "beatriz haddad maia": dict(
        full_name="Beatriz Haddad Maia", ranking=69, age=28, height_cm=174,
        plays="Left-handed", turned_pro=2012,
        career_wins=248, career_losses=162, career_high_rank=11,
        hard_wins=118, hard_losses=84,
        clay_wins=102, clay_losses=64,
        grass_wins=28,  grass_losses=14,
        ytd_wins=1, ytd_losses=6,
        recent_form=["W","W","L","W","W","L","W","W","L","W"],
    ),
    "hailey baptiste": dict(
        full_name="Hailey Baptiste", ranking=45, age=23, height_cm=178,
        plays="Right-handed", turned_pro=2019,
        career_wins=95,  career_losses=82, career_high_rank=58,
        hard_wins=52, hard_losses=44,
        clay_wins=30, clay_losses=26,
        grass_wins=13, grass_losses=12,
        ytd_wins=13, ytd_losses=6,
        recent_form=["W","W","W","L","W","W","W","L","W","W"],
    ),
    "francesca jones": dict(
        full_name="Francesca Jones", ranking=93, age=24, height_cm=163,
        plays="Right-handed", turned_pro=2017,
        career_wins=72, career_losses=80, career_high_rank=101,
        hard_wins=32, hard_losses=38,
        clay_wins=28, clay_losses=28,
        grass_wins=12, grass_losses=14,
        ytd_wins=6, ytd_losses=7,
        recent_form=["W","L","W","W","L","W","L","W","L","W"],
    ),
    "jennifer brady": dict(
        full_name="Jennifer Brady", ranking=88, age=29, height_cm=175,
        plays="Right-handed", turned_pro=2012,
        career_wins=168, career_losses=128, career_high_rank=13,
        hard_wins=98,  hard_losses=74,
        clay_wins=48,  clay_losses=38,
        grass_wins=22,  grass_losses=16,
        ytd_wins=8, ytd_losses=5,
        recent_form=["W","W","L","W","W","W","L","W","L","W"],
    ),
    "katie boulter": dict(
        full_name="Katie Boulter", ranking=67, age=28, height_cm=180,
        plays="Right-handed", turned_pro=2015,
        career_wins=198, career_losses=152, career_high_rank=24,
        hard_wins=88,  hard_losses=74,
        clay_wins=48,  clay_losses=42,
        grass_wins=62,  grass_losses=36,
        ytd_wins=11, ytd_losses=6,
        recent_form=["L","W","W","L","W","W","L","W","W","L"],
    ),
    "laura siegemund": dict(
        full_name="Laura Siegemund", ranking=53, age=36, height_cm=172,
        plays="Right-handed", turned_pro=2009,
        career_wins=268, career_losses=228, career_high_rank=27,
        hard_wins=108, hard_losses=98,
        clay_wins=122, clay_losses=98,
        grass_wins=38,  grass_losses=32,
        ytd_wins=7, ytd_losses=6,
        recent_form=["L","W","L","W","W","L","W","L","W","L"],
    ),
    "magda linette": dict(
        full_name="Magda Linette", ranking=50, age=32, height_cm=165,
        plays="Right-handed", turned_pro=2009,
        career_wins=352, career_losses=288, career_high_rank=21,
        hard_wins=148, hard_losses=128,
        clay_wins=148, clay_losses=118,
        grass_wins=56,  grass_losses=42,
        ytd_wins=10, ytd_losses=7,
        recent_form=["W","L","W","W","L","W","L","L","W","W"],
    ),
    "mccartney kessler": dict(
        full_name="McCartney Kessler", ranking=51, age=24, height_cm=168,
        plays="Right-handed", turned_pro=2022,
        career_wins=128, career_losses=98, career_high_rank=45,
        hard_wins=62, hard_losses=48,
        clay_wins=42, clay_losses=32,
        grass_wins=24, grass_losses=18,
        ytd_wins=9, ytd_losses=7,
        recent_form=["W","W","W","L","W","L","W","W","L","W"],
    ),
    "sofia kenin": dict(
        full_name="Sofia Kenin", ranking=46, age=26, height_cm=163,
        plays="Right-handed", turned_pro=2016,
        career_wins=248, career_losses=192, career_high_rank=4,
        hard_wins=138, hard_losses=102,
        clay_wins=72,  clay_losses=58,
        grass_wins=38,  grass_losses=32,
        ytd_wins=4, ytd_losses=7,
        recent_form=["L","W","W","L","W","W","W","L","L","W"],
    ),
    "jaqueline cristian": dict(
        full_name="Jaqueline Cristian", ranking=36, age=26, height_cm=168,
        plays="Right-handed", turned_pro=2016,
        career_wins=142, career_losses=118, career_high_rank=60,
        hard_wins=68, hard_losses=58,
        clay_wins=52, clay_losses=42,
        grass_wins=22, grass_losses=18,
        ytd_wins=12, ytd_losses=5,
        recent_form=["W","W","W","W","L","W","W","W","L","W"],
    ),
    "sonay kartal": dict(
        full_name="Sonay Kartal", ranking=56, age=23, height_cm=170,
        plays="Right-handed", turned_pro=2020,
        career_wins=112, career_losses=92, career_high_rank=54,
        hard_wins=52, hard_losses=44,
        clay_wins=38, clay_losses=32,
        grass_wins=22, grass_losses=16,
        ytd_wins=10, ytd_losses=6,
        recent_form=["W","W","L","W","W","W","L","W","L","W"],
    ),
    "zeynep sonmez": dict(
        full_name="Zeynep Sonmez", ranking=83, age=23, height_cm=168,
        plays="Right-handed", turned_pro=2019,
        career_wins=98,  career_losses=88, career_high_rank=62,
        hard_wins=48, hard_losses=44,
        clay_wins=32, clay_losses=28,
        grass_wins=18, grass_losses=16,
        ytd_wins=9, ytd_losses=7,
        recent_form=["W","L","W","W","L","L","W","W","W","L"],
    ),
    "dalma galfi": dict(
        full_name="Dalma Galfi", ranking=87, age=27, height_cm=178,
        plays="Right-handed", turned_pro=2013,
        career_wins=221, career_losses=189, career_high_rank=79,
        # Fixed: hard(115)+clay(120)+grass(11)=246 exceeded career_wins(221).
        # Clay figure was inflated from challenger circuit total. Corrected per user spec.
        hard_wins=94,  hard_losses=82,
        clay_wins=116, clay_losses=99,
        grass_wins=11,  grass_losses=8,
        ytd_wins=8, ytd_losses=7,
        recent_form=["W","W","L","L","L","W","W","L","W","L"],
    ),
    "antonia ruzic": dict(
        full_name="Antonia Ruzic", ranking=55, age=22, height_cm=175,
        plays="Right-handed", turned_pro=2021,
        career_wins=88,  career_losses=78, career_high_rank=75,
        hard_wins=42, hard_losses=38,
        clay_wins=32, clay_losses=28,
        grass_wins=14, grass_losses=12,
        ytd_wins=13, ytd_losses=5,
        recent_form=["L","W","W","W","L","W","L","W","W","L"],
    ),
    "oksana selekhmeteva": dict(
        full_name="Oksana Selekhmeteva", ranking=71, age=22, height_cm=166,
        plays="Right-handed", turned_pro=2020,
        career_wins=72,  career_losses=72, career_high_rank=98,
        # Fixed: all surfaces were exactly 50/50 (placeholder data).
        # Corrected based on her challenger/ITF background: hard-court dominant,
        # limited grass experience. Surface sum (68) < career total (72) is valid
        # as some matches were on indoor hard counted in career but rounded here.
        hard_wins=42, hard_losses=30,   # 61.8% hard win rate — hard-court specialist
        clay_wins=18, clay_losses=18,   # 50.0% on clay — average baseline
        grass_wins=8,  grass_losses=10, # 44.4% on grass — limited exposure
        ytd_wins=8, ytd_losses=7,
        recent_form=["L","W","L","W","W","L","W","L","L","W"],
    ),
    "venus williams": dict(
        full_name="Venus Williams", ranking=730, age=45, height_cm=185,
        plays="Right-handed", turned_pro=1994,
        career_wins=815, career_losses=306, career_high_rank=1,
        hard_wins=425, hard_losses=158,
        clay_wins=182, clay_losses=82,
        grass_wins=208, grass_losses=66,
        ytd_wins=1, ytd_losses=5,
        recent_form=["L","L","W","L","L","L","W","L","L","L"],
    ),
    "tatjana maria": dict(
        full_name="Tatjana Maria", ranking=132, age=36, height_cm=168,
        plays="Right-handed", turned_pro=2006,
        career_wins=348, career_losses=328, career_high_rank=49,
        hard_wins=138, hard_losses=138,
        clay_wins=142, clay_losses=132,
        grass_wins=68,  grass_losses=58,
        ytd_wins=5, ytd_losses=7,
        recent_form=["L","L","W","L","W","L","W","L","L","W"],
    ),
    "sloane stephens": dict(
        full_name="Sloane Stephens", ranking=155, age=32, height_cm=168,
        plays="Right-handed", turned_pro=2009,
        career_wins=418, career_losses=328, career_high_rank=3,
        hard_wins=228, hard_losses=172,
        clay_wins=128, clay_losses=108,
        grass_wins=62,  grass_losses=48,
        ytd_wins=4, ytd_losses=7,
        recent_form=["L","W","L","L","W","L","W","L","L","W"],
    ),
    "camila osorio": dict(
        full_name="Camila Osorio", ranking=58, age=23, height_cm=163,
        plays="Right-handed", turned_pro=2018,
        career_wins=168, career_losses=148, career_high_rank=46,
        hard_wins=72, hard_losses=68,
        clay_wins=78, clay_losses=62,
        grass_wins=18, grass_losses=18,
        ytd_wins=9, ytd_losses=7,
        recent_form=["W","L","W","L","W","W","L","L","W","W"],
    ),
    "jessica bouzas maneiro": dict(
        full_name="Jessica Bouzas Maneiro", ranking=48, age=22, height_cm=162,
        plays="Right-handed", turned_pro=2019,
        career_wins=112, career_losses=102, career_high_rank=68,
        hard_wins=48, hard_losses=46,
        clay_wins=48, clay_losses=42,
        grass_wins=16, grass_losses=14,
        ytd_wins=10, ytd_losses=6,
        recent_form=["W","L","L","W","W","L","W","W","L","L"],
    ),
    "petra marcinko": dict(
        full_name="Petra Marcinko", ranking=76, age=22, height_cm=170,
        plays="Right-handed", turned_pro=2020,
        career_wins=68,  career_losses=72, career_high_rank=118,
        hard_wins=32, hard_losses=34,
        clay_wins=24, clay_losses=26,
        grass_wins=12, grass_losses=12,
        ytd_wins=7, ytd_losses=8,
        recent_form=["L","W","L","L","W","W","L","W","L","L"],
    ),
    "varvara gracheva": dict(
        full_name="Varvara Gracheva", ranking=60, age=24, height_cm=168,
        plays="Right-handed", turned_pro=2018,
        career_wins=128, career_losses=118, career_high_rank=58,
        hard_wins=58, hard_losses=58,
        clay_wins=52, clay_losses=46,
        grass_wins=18, grass_losses=14,
        ytd_wins=8, ytd_losses=5,
        recent_form=["L","W","W","L","W","L","L","W","W","L"],
    ),
    "magdalena frech": dict(
        full_name="Magdalena Frech", ranking=37, age=26, height_cm=172,
        plays="Right-handed", turned_pro=2016,
        career_wins=152, career_losses=128, career_high_rank=51,
        hard_wins=68, hard_losses=58,
        clay_wins=62, clay_losses=52,
        grass_wins=22, grass_losses=18,
        ytd_wins=10, ytd_losses=6,
        recent_form=["W","W","L","W","L","W","W","L","W","L"],
    ),
    "anna blinkova": dict(
        full_name="Anna Blinkova", ranking=92, age=26, height_cm=168,
        plays="Right-handed", turned_pro=2016,
        career_wins=148, career_losses=138, career_high_rank=66,
        hard_wins=68, hard_losses=64,
        clay_wins=52, clay_losses=48,
        grass_wins=28, grass_losses=26,
        ytd_wins=7, ytd_losses=7,
        recent_form=["L","W","L","W","W","L","L","W","W","L"],
    ),
    "solana sierra": dict(
        full_name="Solana Sierra", ranking=63, age=22, height_cm=172,
        plays="Right-handed", turned_pro=2020,
        career_wins=88,  career_losses=82, career_high_rank=88,
        hard_wins=38, hard_losses=36,
        clay_wins=38, clay_losses=34,
        grass_wins=12, grass_losses=12,
        ytd_wins=7, ytd_losses=9,
        recent_form=["W","L","W","W","L","W","L","W","L","W"],
    ),
    "peyton stearns": dict(
        full_name="Peyton Stearns", ranking=74, age=22, height_cm=168,
        plays="Right-handed", turned_pro=2022,
        career_wins=138, career_losses=108, career_high_rank=36,
        hard_wins=62, hard_losses=50,
        clay_wins=52, clay_losses=40,
        grass_wins=24, grass_losses=18,
        ytd_wins=9, ytd_losses=5,
        recent_form=["W","W","L","W","W","W","L","W","W","L"],
    ),
    "emiliana arango": dict(
        full_name="Emiliana Arango", ranking=109, age=27, height_cm=165,
        plays="Right-handed", turned_pro=2016,
        career_wins=98,  career_losses=108, career_high_rank=88,
        hard_wins=42, hard_losses=48,
        clay_wins=42, clay_losses=46,
        grass_wins=14, grass_losses=14,
        ytd_wins=5, ytd_losses=9,
        recent_form=["L","W","L","L","W","L","W","L","W","L"],
    ),
    "ashlyn krueger": dict(
        full_name="Ashlyn Krueger", ranking=79, age=21, height_cm=175,
        plays="Right-handed", turned_pro=2022,
        career_wins=118, career_losses=88, career_high_rank=44,
        hard_wins=58, hard_losses=42,
        clay_wins=42, clay_losses=30,
        grass_wins=18, grass_losses=16,
        ytd_wins=10, ytd_losses=7,
        recent_form=["W","W","W","L","W","W","L","W","W","L"],
    ),
    "yulia putintseva": dict(
        full_name="Yulia Putintseva", ranking=75, age=29, height_cm=160,
        plays="Right-handed", turned_pro=2011,
        career_wins=318, career_losses=278, career_high_rank=28,
        hard_wins=138, hard_losses=122,
        clay_wins=132, clay_losses=118,
        grass_wins=48,  grass_losses=38,
        ytd_wins=9, ytd_losses=6,
        recent_form=["W","L","W","W","L","W","L","W","W","L"],
    ),
    "janice tjen": dict(
        full_name="Janice Tjen", ranking=40, age=22, height_cm=168,
        plays="Right-handed", turned_pro=2021,
        career_wins=62,  career_losses=68, career_high_rank=128,
        hard_wins=28, hard_losses=32,
        clay_wins=22, clay_losses=24,
        grass_wins=12, grass_losses=12,
        ytd_wins=14, ytd_losses=5,
        recent_form=["L","W","L","W","L","L","W","W","L","W"],
    ),
    "sorana cirstea": dict(
        full_name="Sorana Cirstea", ranking=35, age=34, height_cm=175,
        plays="Right-handed", turned_pro=2006,
        career_wins=428, career_losses=378, career_high_rank=21,
        hard_wins=188, hard_losses=168,
        clay_wins=168, clay_losses=148,
        grass_wins=72,  grass_losses=62,
        ytd_wins=13, ytd_losses=4,
        recent_form=["W","W","W","L","W","W","L","W","L","W"],
    ),
    "shuai zhang": dict(
        full_name="Shuai Zhang", ranking=61, age=35, height_cm=168,
        plays="Right-handed", turned_pro=2007,
        career_wins=388, career_losses=368, career_high_rank=26,
        hard_wins=172, hard_losses=162,
        clay_wins=138, clay_losses=132,
        grass_wins=78,  grass_losses=74,
        ytd_wins=8, ytd_losses=7,
        recent_form=["L","L","W","L","L","W","L","W","L","L"],
    ),
    "simona waltert": dict(
        full_name="Simona Waltert", ranking=88, age=23, height_cm=175,
        plays="Right-handed", turned_pro=2019,
        career_wins=98,  career_losses=92, career_high_rank=85,
        hard_wins=42, hard_losses=40,
        clay_wins=38, clay_losses=36,
        grass_wins=18, grass_losses=16,
        ytd_wins=7, ytd_losses=7,
        recent_form=["W","L","W","W","L","W","L","W","L","W"],
    ),
    "ajla tomljanovic": dict(
        full_name="Ajla Tomljanovic", ranking=81, age=31, height_cm=180,
        plays="Right-handed", turned_pro=2011,
        career_wins=248, career_losses=238, career_high_rank=28,
        hard_wins=108, hard_losses=102,
        clay_wins=82,  clay_losses=80,
        grass_wins=58,  grass_losses=56,
        ytd_wins=7, ytd_losses=7,
        recent_form=["L","W","L","L","W","L","W","L","W","L"],
    ),
    "elsa jacquemot": dict(
        full_name="Elsa Jacquemot", ranking=62, age=22, height_cm=170,
        plays="Right-handed", turned_pro=2020,
        career_wins=65, career_losses=52, career_high_rank=65,
        hard_wins=28, hard_losses=25,
        clay_wins=30, clay_losses=20,
        grass_wins=7,  grass_losses=7,
        ytd_wins=7, ytd_losses=8,
        recent_form=["L","W","L","W","L","W","W","L","W","L"],
    ),
    "paula badosa": dict(
        full_name="Paula Badosa", ranking=27, age=28, height_cm=174,
        plays="Right-handed", turned_pro=2016,
        career_wins=212, career_losses=148, career_high_rank=2,
        hard_wins=108, hard_losses=72,
        clay_wins=82,  clay_losses=58,
        grass_wins=22,  grass_losses=18,
        ytd_wins=9, ytd_losses=4,
        recent_form=["W","W","W","L","W","W","W","L","W","W"],
    ),
    "qualifier": dict(
        full_name="Qualifier", ranking=118, age=24, height_cm=170,
        plays="Right-handed", turned_pro=2020,
        career_wins=58,  career_losses=54, career_high_rank=110,
        hard_wins=26, hard_losses=26,
        clay_wins=22, clay_losses=20,
        grass_wins=10, grass_losses=8,
        ytd_wins=5, ytd_losses=4,
        recent_form=["W","L","W","W","L","W","L","L","W","W"],
    ),
    "darja vidmanova": dict(
        full_name="Darja Vidmanova", ranking=118, age=20, height_cm=175,
        plays="Right-handed", turned_pro=2021,
        career_wins=88, career_losses=60, career_high_rank=44,
        hard_wins=45, hard_losses=28,
        clay_wins=32, clay_losses=22,
        grass_wins=11, grass_losses=10,
        ytd_wins=5, ytd_losses=8,
        recent_form=["W","W","L","W","W","W","L","W","W","L"],
    ),
    # ── Name-registry entries: full_name only (all stats fetched live from jsfrags) ──
    # Add new players here with just physical attributes — no manual stat maintenance needed.
    "iga swiatek": dict(
        full_name="Iga Swiatek", age=24, height_cm=175, plays="Right-handed",
        turned_pro=2016, career_wins=370, career_losses=80, career_high_rank=1,
    ),
    "aryna sabalenka": dict(
        full_name="Aryna Sabalenka", age=26, height_cm=182, plays="Right-handed",
        turned_pro=2015, career_wins=350, career_losses=130, career_high_rank=1,
    ),
    "coco gauff": dict(
        full_name="Coco Gauff", age=21, height_cm=183, plays="Right-handed",
        turned_pro=2020, career_wins=220, career_losses=90, career_high_rank=2,
    ),
    "jessica pegula": dict(
        full_name="Jessica Pegula", age=31, height_cm=170, plays="Right-handed",
        turned_pro=2010, career_wins=240, career_losses=160, career_high_rank=3,
    ),
    "qinwen zheng": dict(
        full_name="Qinwen Zheng", age=22, height_cm=181, plays="Right-handed",
        turned_pro=2019, career_wins=150, career_losses=95, career_high_rank=5,
    ),
    "elena rybakina": dict(
        full_name="Elena Rybakina", age=25, height_cm=184, plays="Right-handed",
        turned_pro=2016, career_wins=195, career_losses=100, career_high_rank=4,
    ),
    "mirra andreeva": dict(
        full_name="Mirra Andreeva", age=18, height_cm=172, plays="Right-handed",
        turned_pro=2023, career_wins=85, career_losses=55, career_high_rank=12,
    ),
    "diana shnaider": dict(
        full_name="Diana Shnaider", age=20, height_cm=178, plays="Left-handed",
        turned_pro=2021, career_wins=100, career_losses=60, career_high_rank=10,
    ),
    "emma navarro": dict(
        full_name="Emma Navarro", age=23, height_cm=175, plays="Right-handed",
        turned_pro=2022, career_wins=95, career_losses=55, career_high_rank=8,
    ),
    "danielle collins": dict(
        full_name="Danielle Collins", age=31, height_cm=170, plays="Right-handed",
        turned_pro=2016, career_wins=210, career_losses=145, career_high_rank=7,
    ),
    "amanda anisimova": dict(
        full_name="Amanda Anisimova", age=23, height_cm=175, plays="Right-handed",
        turned_pro=2018, career_wins=165, career_losses=110, career_high_rank=21,
    ),
    "madison keys": dict(
        full_name="Madison Keys", age=30, height_cm=178, plays="Right-handed",
        turned_pro=2009, career_wins=420, career_losses=250, career_high_rank=7,
    ),
    "caroline ruse": dict(
        full_name="Caroline Ruse", ranking=120, age=26, height_cm=168, plays="Right-handed",
        turned_pro=2017, career_wins=110, career_losses=90, career_high_rank=91,
        hard_wins=55, hard_losses=45, ytd_wins=3, ytd_losses=4,
        recent_form=["W","L","W","L","L","W","L","W","W","L"],
    ),
    "karolina muchova": dict(
        full_name="Karolina Muchova", age=28, height_cm=176, plays="Right-handed",
        turned_pro=2016, career_wins=175, career_losses=115, career_high_rank=8,
    ),
    "barbora krejcikova": dict(
        full_name="Barbora Krejcikova", age=29, height_cm=172, plays="Right-handed",
        turned_pro=2013, career_wins=290, career_losses=170, career_high_rank=2,
    ),
    "anna kalinskaya": dict(
        full_name="Anna Kalinskaya", age=26, height_cm=176, plays="Right-handed",
        turned_pro=2016, career_wins=130, career_losses=95, career_high_rank=11,
    ),
    "liudmila samsonova": dict(
        full_name="Liudmila Samsonova", age=26, height_cm=175, plays="Right-handed",
        turned_pro=2015, career_wins=170, career_losses=105, career_high_rank=12,
    ),
    "jasmine paolini": dict(
        full_name="Jasmine Paolini", age=29, height_cm=163, plays="Right-handed",
        turned_pro=2013, career_wins=270, career_losses=180, career_high_rank=4,
    ),
    "victoria mboko": dict(
        full_name="Victoria Mboko", age=19, height_cm=173, plays="Right-handed",
        turned_pro=2022, career_wins=60, career_losses=40, career_high_rank=50,
    ),
    "elina svitolina": dict(
        full_name="Elina Svitolina", age=30, height_cm=175, plays="Right-handed",
        turned_pro=2010, career_wins=500, career_losses=220, career_high_rank=3,
    ),
    "daria kasatkina": dict(
        full_name="Daria Kasatkina", age=27, height_cm=168, plays="Right-handed",
        turned_pro=2014, career_wins=280, career_losses=180, career_high_rank=8,
    ),
    "clara tauson": dict(
        full_name="Clara Tauson", age=22, height_cm=179, plays="Right-handed",
        turned_pro=2020, career_wins=120, career_losses=80, career_high_rank=25,
    ),
    "jelena ostapenko": dict(
        full_name="Jelena Ostapenko", age=27, height_cm=175, plays="Right-handed",
        turned_pro=2012, career_wins=300, career_losses=220, career_high_rank=5,
    ),
    "naomi osaka": dict(
        full_name="Naomi Osaka", age=27, height_cm=180, plays="Right-handed",
        turned_pro=2013, career_wins=230, career_losses=90, career_high_rank=1,
    ),
    "victoria azarenka": dict(
        full_name="Victoria Azarenka", age=35, height_cm=183, plays="Right-handed",
        turned_pro=2002, career_wins=600, career_losses=270, career_high_rank=1,
    ),
    "donna vekic": dict(
        full_name="Donna Vekic", age=28, height_cm=180, plays="Right-handed",
        turned_pro=2010, career_wins=250, career_losses=210, career_high_rank=19,
    ),
    "alexandra eala": dict(
        full_name="Alexandra Eala", age=19, height_cm=163, plays="Right-handed",
        turned_pro=2021, career_wins=80, career_losses=60, career_high_rank=29,
    ),
    "marie bouzkova": dict(
        full_name="Marie Bouzkova", age=26, height_cm=170, plays="Right-handed",
        turned_pro=2016, career_wins=120, career_losses=100, career_high_rank=30,
    ),
    "belinda bencic": dict(
        full_name="Belinda Bencic", age=27, height_cm=175, plays="Right-handed",
        turned_pro=2012, career_wins=340, career_losses=180, career_high_rank=4,
    ),
}
